# Generated by Django 2.0.7 on 2019-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=18)),
                ('account_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget_setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=18)),
                ('account_name', models.CharField(max_length=255)),
                ('account_budget', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='General_paramter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('general_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_code', models.CharField(blank=True, max_length=10, null=True)),
                ('purpose_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_defination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('pro_category', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('pro_period', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('relation_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
